PayPal core
===========
Micromata GmbH, Kai Reinhard, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2018, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Documentation

For documentation of this library please refer the README in the parent directory.

== General information of how to publish to Maven central

=== Publishing to Maven Central

This section describes in general how to publish to maven central any artifact.

==== Creating an account for Sonatype
Create an account at https://oss.sonatype.org.

==== Granting the account for your group

Open a JIRA issue at https://issues.sonatype.org for project `OSSRH` and request the permissions.

==== Signing

Create

.~/.gradle/gradle.properties
----
signing.gnupg.keyName=<your key name / id>
signing.gnupg.passphrase=<the key's passphrase>
mavenUser=<your maven user name>
mavenPassword=<your maven password>
----

Ensure that `GRADLE_USER_HOME` environment variable points to `~/.gradle` and you key is published under
http://pool.sks-keyservers.net:11371 and http://keys.gnupg.net:11371/


==== Staging a release

Refer https://central.sonatype.org/pages/releasing-the-deployment.html.

Check:

1. Download snapshot and release artifacts from group https://oss.sonatype.org/content/groups/public/de/micromata/paypal/paypal-core
2. Download snapshot, release and staged artifacts from staging group https://oss.sonatype.org/content/groups/staging/de/micromata/paypal/paypal-core
3. Check downloads
4. Press Release button at the top.

